/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sveKlase_Formula */

#ifndef _Included_sveKlase_Formula
#define _Included_sveKlase_Formula
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sveKlase_Formula
 * Method:    getPrecedence
 * Signature: (C)I
 */
JNIEXPORT jint JNICALL Java_sveKlase_Formula_getPrecedence
  (JNIEnv *, jobject, jchar);

#ifdef __cplusplus
}
#endif
#endif
